modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "efficiency"
version = "${version}"
displayName = "Efficiency"
logoFile = "icon.png"
authors = "angxd"
description = '''
Easy-to-use ingame mod browser & installer
'''

[[dependencies.efficiency]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.efficiency]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
